arquivo = open("text.txt", "r")

conteudo1 = arquivo.read()
conteudo2 = arquivo.readline()
conteudo3 = arquivo.readlines()
print("\n")
print("---------conteudo com read------------")
print("\n")
print(f"Tipo de conteúdo: {type(conteudo1)}")
print(f"Todo conteudo sem formatação de texto \n{repr(conteudo1)}")
print("\n")
print("---------conteudo com readline------------")
print("\n")
print(f"Tipo de conteúdo: {type(conteudo2)}")
print(repr(conteudo2))
print("\n")
print("---------conteudo com readlines------------")
print("\n")
print(f"Tipo de conteúdo: {type(conteudo3)}")
print(repr(conteudo3))
print("\n")
print("-------------------------------------------")

arquivo.close()
